name: Run Tests and Display Markdown Report

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-md

    - name: Run tests and generate Markdown report
      run: |
        pytest --md=report.md

    - name: Display Markdown Report in Summary
      run: |
        echo "# Test Results" >> $GITHUB_STEP_SUMMARY
        cat report.md >> $GITHUB_STEP_SUMMARY
